// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  rich_text: dynamic(() => import("./RichText")),
  solar_system: dynamic(() => import("./SolarSystem")),
};
